//This Contains the constants for actions
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';

export const REQUEST_ROBOTS_LOADING = 'REQUEST_ROBOTS_LOADING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';